# Generated by Django 5.0.1 on 2024-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=40)),
                ('actor', models.CharField(max_length=40)),
                ('box_office', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
